[tool.poetry]
name = "mylib"
description = "shared code"
version = "0.1.0"
authors = []
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.15"

[tool.poetry.dev-dependencies]
pytest = "^4.5"
pytest-cov = "^2.7"
